appName: sosialhjelp-soknad-dev
idportenEnabled: false
ingresses: []
wonderwallInstance: wonderwall-soknad-dev
outboundRules: [sosialhjelp-soknad-api-dev]
outboundExternalHosts: []
livenessPath: /sosialhjelp/soknad/internal/isAlive
env:
  UMAMI_ID: "00a054e3-9928-4882-8e82-235940dfc04b"
requests:
  cpu: 50m
  memory: 100Mi
limts:
  memory: 400Mi
replicas:
  min: 1
  max: 2
