FROM node as node-builder

ADD / /source
WORKDIR /source
ENV CI=true
RUN npm ci && npm run build

FROM node as node-image

WORKDIR /app
COPY --from=node-builder /source/build /app
RUN echo "Fra config yaml, variable test: $test"
COPY heroku.js /app
COPY heroku-index.html /app/index.html

RUN npm install express

CMD ["node", "heroku.js"]
