FROM navikt/java:8

WORKDIR /app

COPY web/target/soknadsosialhjelp.jar /app/app.jar

# FIXME
COPY ./web/target/classes/webapp/WEB-INF/heroku-web.xml /app/web/target/classes/webapp/WEB-INF/heroku-web.xml

ENV HEROKU=true

CMD ["/bin/sh", "start.sh"]