FROM node as node-builder

ADD / /source
WORKDIR /source
ENV CI=true
RUN npm ci && npm run build

FROM node as node-image

WORKDIR /app
COPY --from=node-builder /source/build /app
COPY heroku.js /app
COPY heroku-index.html /app/index.html

RUN npm install express

# TODO Legg til logikk for master vs. feature branch
#CMD sed -i 's!sosialhjelp/soknad!'$HEROKU_APP_NAME'/sosialhjelp/soknad!g' index.html && node heroku.js
CMD ["node", "heroku.js"]
