apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{applicationName}}
  namespace: {{namespace}}
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8080
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /prometheus
{{#if gcpAccessPolicy}}
  accessPolicy:
    outbound:
      external:
        - host: "appres.nav.no"
        - host: "nav.psplugin.com"
      rules: []
{{/if}}
  liveness:
    path: /sosialhjelp/soknad/internal/isAlive
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/soknad/internal/isAlive
    initialDelay: 5
    timeout: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 40m
      memory: 128Mi
  replicas:
    min: 2
    max: 2
  env:
    - name: DEKORATOR_MILJO
      value: {{dekoratorMiljo}}
    - name: UNLEASH_API_URL
      value: https://unleash.nais.io/api/
