minimumReleaseAge: 10080

allowBuilds:
  "@parcel/watcher": false
  "@swc/core": false
  esbuild: false
  msw: false
  protobufjs: false
  sharp: false
  unrs-resolver: false

overrides:
  lru-cache: "11.2.7"
  postcss@<8.5.10: ">=8.5.10"
  protobufjs: ^7.5.5
