apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-soknad-{{postfix}}
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{image}}
  port: 8080
  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
  accessPolicy:
    outbound:
      rules:
        - application: sosialhjelp-soknad-api
      external:
        {{#each externalOutboundAccesses as |url|}}
        - host: {{url}}
        {{/each}}
  liveness:
    path: /sosialhjelp/soknad/internal/isAlive
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/soknad/internal/isAlive
    initialDelay: 5
    timeout: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 1m
      memory: 50Mi
  {{#if idportenEnabled}}
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  {{/if}}
  replicas:
    min: 1
    max: 1
  env:
  {{#each env as |env|}}
  - name: {{@key}}
    value: {{env}}
  {{/each}}