apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ appName }}
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{image}}
  port: 8080
  {{#if ingresses}}
  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}{{/each}}
  {{/if}}
  accessPolicy:
    inbound:
      rules:
        - application: wonderwall-soknad
    outbound:
      rules:
        - application: sosialhjelp-driftsmeldinger
        - application: sosialhjelp-soknad-api
        - application: nav-dekoratoren
          namespace: personbruker
{{#if outboundExternalHosts}}
      external:
        {{#each outboundExternalHosts as |url|}}
        - host: {{url}}{{/each}}
{{/if}}
  liveness:
    path: {{ livenessPath }}
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: {{ livenessPath }}
    initialDelay: 5
    timeout: 1
  resources:
    limits:
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi
{{#if idportenEnabled}}
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
{{/if}}
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  replicas:
    min: 2
    max: 4
{{#if env}}
  env:
  {{#each env as |env|}}
  - name: {{@key}}
    value: {{env}}
  {{/each}}
{{/if}}
