export enum REST_STATUS {
	OK = "OK",
	FEILET = "FEILET",
	PENDING = "PENDING",
	INITIALISERT = "INITIALISERT"
}

export enum RestStatus {
	NOT_ASKED = "NOT_ASKED",
	LOADING = "LOADING",
	SUCCESS = "SUCCESS",
	FAILURE = "FAILURE"
}
