name: 'Build Docker Image'
description: 'Create tag and release, Build code, artifact and Docker Image.'

inputs:
  prefix:
    required: true
    description: 'Tag prefix (prod/dev)'

outputs:
  full-tag:
    description: 'Full tag'
    value: ${{ steps.final-tag.outputs.tag }}

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v4

  - name: 'Create artifact version'
    id: artifact-version
    uses: navikt/sosialhjelp-ci/actions/create-artifact-version@main

  - name: 'Tag with prefix'
    id: final-tag
    run: |
      echo "tag=${{ inputs.prefix }}-${{ steps.artifact-version.outputs.version }}" >> $GITHUB_OUTPUT
    shell: bash

  - name: 'Login to GitHub Docker Registry if GitHub Token Provided'
    uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ env.WORKFLOW_TOKEN }}

  - name: Build and push
    uses: docker/build-push-action@v6
    with:
      push: true
      tags: "${{ env.DOCKER_IMAGE }}:latest,${{ env.DOCKER_IMAGE }}:${{ steps.final-tag.outputs.tag }}"
      secrets: "NODE_AUTH_TOKEN=${{ env.READER_TOKEN }}"
      build-args: "DIGISOS_ENV=${{ inputs.prefix }}"

  - name: 'Release Tag'
    uses: ncipollo/release-action@v1
    env:
      GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
    with:
      tag: ${{ steps.final-tag.outputs.tag }}
      commit: ${{ github.sha }}
      allowUpdates: true
