angular.module('nav.soknadsosialhjelp.soknad', [
    'nav.accordion',
    'nav.soknadsosialhjelp.soknad.arbeidbolk',
    'nav.soknadsosialhjelp.soknad.familiebolk',
    'nav.soknadsosialhjelp.soknad.begrunnelsebolk',
    'nav.soknadsosialhjelp.soknad.bosituasjonbolk',
    'nav.soknadsosialhjelp.soknad.inntektbolk',
    'nav.bolker',
    'nav.cms',
    'nav.services.soknad',
    'nav.fremdriftsindikator',
    'nav.miljovariabler',
    'nav.modal',
    'nav.modalsideskall',
    'nav.navfaktum',
    'nav.sidetittel',
    'nav.stickyFeilmelding',
    'nav.stegindikator',
    'nav.sistLagret',
    'nav.stickybunn',
    'nav.validering',
    'ngResource'
]);

require('angular-cms');
require('angular-miljovariabler');
require('angular-soknad-bolker');
require('angular-soknad-fremdriftsindikator');
require('angular-soknad-tittel');
require('angular-modal');
require('angular-modalsideskall');
require('angular-navfaktum');
require('angular-soknad-validering');
require('angular-stegindikator');
require('angular-accordion');
require('angular-soknad-sistlagret');
require('angular-soknad-stickybunn');

require('./soknadDirective');
require('./soknadBolkService');
require('./bolker/arbeid/arbeidbolkModule');
require('./bolker/familie/familiebolkModule');
require('./bolker/begrunnelse/begrunnelsebolkModule');
require('./bolker/bosituasjon/bosituasjonbolkModule');
require('./bolker/inntekt/inntektbolkModule');