apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-soknad-mock
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://digisos.ekstern.dev.nav.no/sosialhjelp/soknad"
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.dev.nav.no
        - host: dekoratoren.ekstern.dev.nav.no
        - host: digisos.ekstern.dev.nav.no
        - host: www.dev.nav.no
  liveness:
    path: /sosialhjelp/soknad/internal/isAlive
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/soknad/internal/isAlive
    initialDelay: 5
    timeout: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 1m
      memory: 50Mi
  replicas:
    min: 1
    max: 1
  env:
    - name: DEKORATOR_MILJO
      value: dev