apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: wonderwall-soknad-intern
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "150M"
spec:
  image: europe-north1-docker.pkg.dev/nais-io/nais/images/wonderwall:latest
  port: 8080
  ingresses:
    - "https://www.ansatt.nav.no/sosialhjelp/soknad"
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
      rules:
        - application: sosialhjelp-soknad-intern
  resources:
    limits:
      cpu: "2"
      memory: 256Mi
    requests:
      cpu: "20m"
      memory: 50Mi
  redis:
    - access: read
      instance: wonderwall
  liveness:
    initialDelay: 20
    path: /sosialhjelp/soknad/oauth2/ping
  readiness:
    initialDelay: 20
    path: /sosialhjelp/soknad/oauth2/ping
  replicas:
    min: 2
    max: 2
  envFrom:
    - secret: wonderwall-redis
  env:
    - name: WONDERWALL_SSO_ENABLED
      value: "true"
    - name: WONDERWALL_SSO_MODE
      value: proxy
    - name: WONDERWALL_AUTO_LOGIN
      value: "true"
    - name: WONDERWALL_INGRESS
      value: https://www.ansatt.nav.no/sosialhjelp/soknad
    - name: WONDERWALL_UPSTREAM_HOST
      value: sosialhjelp-soknad-intern:80
    - name: WONDERWALL_BIND_ADDRESS
      value: 0.0.0.0:8080
    - name: WONDERWALL_METRICS_BIND_ADDRESS
      value: 0.0.0.0:7565
    - name: WONDERWALL_SHUTDOWN_GRACEFUL_PERIOD
      value: 30s
    - name: WONDERWALL_SHUTDOWN_WAIT_BEFORE_PERIOD
      value: 7s
    - name: WONDERWALL_LOG_LEVEL
      value: debug
    - name: WONDERWALL_SSO_SESSION_COOKIE_NAME
      value: no.sosialhjelp.wonderwall.session
    - name: WONDERWALL_SSO_SERVER_URL
      value: https://www.nav.no/sosialhjelp/wonderwall
    - name: WONDERWALL_REDIS_URI
      value: $(REDIS_URI_WONDERWALL)
    - name: WONDERWALL_REDIS_USERNAME
      value: $(REDIS_USERNAME_WONDERWALL)
    - name: WONDERWALL_REDIS_PASSWORD
      value: $(REDIS_PASSWORD_WONDERWALL)
    - name: WONDERWALL_SESSION_MAX_LIFETIME
      value: 59m
    - name: WONDERWALL_SESSION_REFRESH_AUTO
      value: "false"
