export const opplysningsRekkefolge: string[] = [
    "lonnslipp|arbeid",
    "sluttoppgjor|arbeid",
    "student|vedtak",
    "barnebidrag|betaler",
    "barnebidrag|mottar",
    "samvarsavtale|barn",
    "husleiekontrakt|husleiekontrakt",
    "husleiekontrakt|kommunal",
    "bostotte|vedtak",
    "kontooversikt|brukskonto",
    "kontooversikt|bsu",
    "kontooversikt|sparekonto",
    "kontooversikt|livsforsikring",
    "kontooversikt|aksjer",
    "kontooversikt|annet",
    "dokumentasjon|utbytte",
    "salgsoppgjor|eiendom",
    "dokumentasjon|forsikringsutbetaling",
    "dokumentasjon|annetinntekter",
    "faktura|husleie",
    "faktura|strom",
    "faktura|kommunaleavgifter",
    "faktura|oppvarming",
    "nedbetalingsplan|avdraglaan",
    "dokumentasjon|annetboutgift",
    "faktura|fritidsaktivitet",
    "faktura|barnehage",
    "faktura|sfo",
    "faktura|tannbehandling",
    "faktura|annetbarnutgift",
    "skattemelding|skattemelding",
    "annet|annet"
];

export const gruppeRekkefolge: string[] = [
    "arbeid",
    "familie",
    "bosituasjon",
    "inntekt",
    "utgifter",
    "generelle vedlegg",
    "andre utgifter",
    "ukjent"
];