name: Build and deploy to dev
on:
  workflow_call:
    inputs:
      config-file-name:
        required: true
        type: string
    secrets:
      api_deploy_token:
        required: true
  workflow_dispatch:
    inputs:
      config-file-name:
        description: 'Config-fil som skal deployes'
        required: true
        default: 'dev-sbs'
        type: choice
        options:
          - 'dev'
          - 'mock'
          - 'dev-sbs'

# FIXME: Legg til docker layer caching, f.eks. https://github.com/marketplace/actions/build-docker-images-using-cache
jobs:
  build:
    name: Build and deploy to dev
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}/sosialhjelp-soknad
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
      - name: Sett env variabler og sett cluster basert på config-file
        run: |
          echo "CONFIG_FILE=${{ inputs.config-file-name }}" >> $GITHUB_ENV

          if [[ ${{ inputs.config-file-name }} = 'dev-sbs' ]]; then
            echo "CLUSTER_NAME=dev-sbs" >> $GITHUB_ENV
          else
            echo "CLUSTER_NAME=dev-gcp" >> $GITHUB_ENV
          fi
          echo "Deployer til ${{ env.CLUSTER_NAME }}"
      - name: Copy env-file for dev
        run: cp nais/dev/${{ env.CONFIG_FILE }}.env .env.local
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Run tests
        run: npm run test
      - name: Build less
        run: npm run build:css
      - name: Build application
        run: npm run build
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create artifact version
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master
      - name: Get complete tag
        run: |
          echo "COMPLETE_TAG=${{ env.CONFIG_FILE }}-$( date +%s )-${{ steps.artifact-version.outputs.version }}" >> $GITHUB_ENV
      - name: Create docker image tags
        run: |
          echo "DOCKER_TAG=${{ env.DOCKER_IMAGE }}:${{ env.COMPLETE_TAG }}" >> $GITHUB_ENV
      - name: Build docker image
        run: docker build -t ${{ env.DOCKER_TAG }} .
      - name: Push docker image
        run: |
          docker push ${{ env.DOCKER_TAG }}
      - name: Create tag and release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.COMPLETE_TAG }}
          release_name: ${{ env.COMPLETE_TAG }}
          commitish: ${{ github.sha }}
      - name: Deploy til dev - ${{ github.event.inputs.config-file-name }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY != '' && secrets.NAIS_DEPLOY_APIKEY || secrets.api_deploy_token }}
          RESOURCE: nais.yaml
          CLUSTER: ${{ env.CLUSTER_NAME }}
          VARS: nais/dev/${{ env.CONFIG_FILE }}.json
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.DOCKER_TAG }}