name: Build and deploy to dev
on:
  workflow_call:
    inputs:
      config-file-name:
        required: true
        type: string
      cluster:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      config-file-name:
        description: 'Config-fil (uten .json) som skal deployes'
        required: true
        default: 'dev-sbs-intern'
      cluster:
        description: 'Cluster å deploye til (dev-sbs, labs-gcp eller dev-gcp)'
        required: true
        default: 'dev-sbs'

# FIXME: Legg til docker layer caching, f.eks. https://github.com/marketplace/actions/build-docker-images-using-cache
jobs:
  build:
    name: Build and deploy to dev
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Sett cluster og config to env variables
        run: |
          echo "CLUSTER_NAME=${{ inputs.cluster != '' && inputs.cluster || github.event.inputs.cluster }}" >> $GITHUB_ENV
          echo "CONFIG_FILE=${{ inputs.config-file-name  != '' && inputs.config-file-name  || github.event.inputs.config-file-name }}" >> $GITHUB_ENV
      - name: Copy env-file for dev
        run: cp nais/dev/${{ env.CONFIG_FILE }}.env .env.local
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build less
        run: npm run build:css
      - name: Build application
        run: npm run build
      - name: Login to GitHub package registry
        run: |
          echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_REPOSITORY} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create artifact version
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master
      - name: Get complete tag
        run: |
          echo "COMPLETE_TAG=${{ env.CONFIG_FILE }}-$( date +%s )-${{ steps.artifact-version.outputs.version }}" >> $GITHUB_ENV
      - name: Create docker image tags
        run: |
          echo "DOCKER_TAG=${{ env.DOCKER_IMAGE }}:${{ env.COMPLETE_TAG }}" >> $GITHUB_ENV
      - name: Build docker image
        run: docker build -t ${{ env.DOCKER_TAG }} .
      - name: Push docker image
        run: |
          docker push ${{ env.DOCKER_TAG }}
      - name: Create tag and release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.COMPLETE_TAG }}
          release_name: ${{ env.COMPLETE_TAG }}
          commitish: ${{ github.sha }}
      - name: Deploy til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais.yaml
          CLUSTER: ${{ env.CLUSTER_NAME }}
          VARS: nais/dev/${{ env.CONFIG_FILE }}.json
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.DOCKER_TAG }}