name: "Deploy Wonderwall for App"

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Wonderwall prod, preprod eller dev?'
        required: true
        default: 'dev'
        type: choice
        options:
          - 'dev'
          - 'preprod'
          - 'prod'

jobs:
  deploy-gcp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - id: set-cluster
        run: |
          if [ "${{ inputs.env }}" == "prod" ]; then
            echo "CLUSTER=prod-gcp" >> $GITHUB_ENV
          else
            echo "CLUSTER=dev-gcp" >> $GITHUB_ENV
          fi

      - name: "Deploy to ${{ inputs.env }}"
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: wonderwall/${{ inputs.env }}/wonderwall.yml
          CLUSTER: ${{ env.CLUSTER }}
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
