name: "Restart all environments"
on:
  schedule:
    - cron: "0 2 * * *" # 02:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  deploy_test_envs:
    strategy:
      fail-fast: false
      matrix:
        env: [dev, mock, preprod]
    uses: ./.github/workflows/build_deploy_gcp_dev.yml
    with:
      environment: ${{ matrix.env }}
      skip_playwright: ${{ github.event_name == 'schedule' }}
    secrets: inherit

  deploy_prod:
    needs: deploy_test_envs
    uses: ./.github/workflows/build_deploy_gcp_prod.yml
    with:
      skip_playwright: ${{ github.event_name == 'schedule' }}
    secrets: inherit