name: "Restart all environments"
on:
  schedule:
    - cron: "0 2 * * *" # 02:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy_test_envs:
    strategy:
      fail-fast: false
      matrix:
        env: [dev, mock]
    uses: ./.github/workflows/build_deploy_gcp_dev.yml
    with:
      environment: ${{ matrix.env }}
    secrets: inherit

  deploy_prod:
    needs: deploy_test_envs
    uses: ./.github/workflows/build_deploy_gcp_prod.yml
    secrets: inherit